export const dashboardTableData = [
  {
    customer: "Alice Johnson",
    amount: "₹118",
    dueDate: "1 Dec 2025",
    status: "Paid",
    route: "/invoices/1",
  },
  {
    customer: "Bob Smith",
    amount: "₹220",
    dueDate: "3 Dec 2025",
    status: "Paid",
    route: "/invoices/2",
  },
  {
    customer: "Charlie Brown",
    amount: "₹450",
    dueDate: "5 Dec 2025",
    status: "Paid",
    route: "/invoices/3",
  },
  {
    customer: "Diana Ross",
    amount: "₹99",
    dueDate: "7 Dec 2025",
    status: "Paid",
    route: "/invoices/4",
  },
  {
    customer: "Ethan Hunt",
    amount: "₹560",
    dueDate: "9 Dec 2025",
    status: "Paid",
    route: "/invoices/5",
  },
  {
    customer: "Fiona Green",
    amount: "₹180",
    dueDate: "11 Dec 2025",
    status: "Paid",
    route: "/invoices/6",
  },
  {
    customer: "George Miller",
    amount: "₹300",
    dueDate: "13 Dec 2025",
    status: "Paid",
    route: "/invoices/7",
  },
  {
    customer: "Hannah Lee",
    amount: "₹720",
    dueDate: "15 Dec 2025",
    status: "Paid",
    route: "/invoices/8",
  },
  {
    customer: "Ivan Petrov",
    amount: "₹150",
    dueDate: "17 Dec 2025",
    status: "Paid",
    route: "/invoices/9",
  },
  {
    customer: "Julia Roberts",
    amount: "₹999",
    dueDate: "19 Dec 2025",
    status: "Paid",
    route: "/invoices/10",
  },
];
