export const sectionWiseSummaryConfig = {
  columns: [
    { label: "Section", key: "section" },
    { label: "Description", key: "description" },
    { label: "No. of Records", key: "records" },
    { label: "Taxable Value", key: "taxableValue" },
    { label: "CGST", key: "cgst" },
    { label: "SGST", key: "sgst" },
    { label: "IGST", key: "igst" },
    { label: "CESS", key: "cess" },
    { label: "Total Value", key: "totalValue" },
  ],

  data: [
    {
      section: "4A, 4B, 4C, 6B",
      description: "B2B Invoices - Supplies made to Registered Persons",
      records: 4,
      taxableValue: "₹6,50,000",
      cgst: "₹54,240",
      sgst: "₹54,240",
      igst: "₹81,000",
      cess: "₹0",
      totalValue: "₹8,21,480",
    },
    {
      section: "5A, 5B",
      description:
        "B2C (Large) - Supplies to Unregistered Persons (>2.5 Lakh)",
      records: 2,
      taxableValue: "₹3,50,000",
      cgst: "-",
      sgst: "-",
      igst: "₹63,000",
      cess: "₹0",
      totalValue: "₹4,13,000",
    },
    {
      section: "7",
      description:
        "B2C (Small) - Supplies to Unregistered Persons (Other)",
      records: 15,
      taxableValue: "₹1,25,000",
      cgst: "₹11,250",
      sgst: "₹11,250",
      igst: "₹0",
      cess: "₹0",
      totalValue: "₹1,47,500",
    },
    {
      section: "6A",
      description: "Exports Invoices - With Payment of Tax",
      records: 1,
      taxableValue: "₹5,00,000",
      cgst: "-",
      sgst: "-",
      igst: "₹90,000",
      cess: "₹0",
      totalValue: "₹5,90,000",
    },
    {
      section: "9B",
      description: "Credit/Debit Notes (Registered)",
      records: 1,
      taxableValue: "-₹25,000",
      cgst: "-₹2,250",
      sgst: "-₹2,250",
      igst: "-",
      cess: "₹0",
      totalValue: "-₹29,500",
      isNegative: true,
    },
    {
      section: "8",
      description: "Nil Rated, Exempted, Non-GST Supplies",
      records: 8,
      taxableValue: "₹45,000",
      cgst: "-",
      sgst: "-",
      igst: "-",
      cess: "-",
      totalValue: "₹45,000",
    },
    {
      section: "Total",
      description: "",
      records: "",
      taxableValue: "₹16,45,000",
      cgst: "₹54,240",
      sgst: "₹54,240",
      igst: "₹2,34,000",
      cess: "-",
      totalValue: "₹19,87,480",
      isTotal: true,
    },
  ],
};
