export const hsnWiseSummaryConfig = {
  columns: [
    { label: "HSN Code", key: "hsnCode" },
    { label: "Description", key: "description" },
    { label: "UQC", key: "uqc" },
    { label: "Total Quantity", key: "quantity" },
    { label: "Taxable Value", key: "taxableValue" },
    { label: "Tax Rate", key: "taxRate" },
    { label: "CGST", key: "cgst" },
    { label: "SGST", key: "sgst" },
    { label: "IGST", key: "igst" },
  ],

  data: [
    {
      hsnCode: "998314",
      description: "IT Software Services",
      uqc: "OTH",
      quantity: 12,
      taxableValue: "₹850,000",
      taxRate: "18%",
      cgst: "₹45,240",
      sgst: "₹45,240",
      igst: "₹107,100",
    },
    {
      hsnCode: "847330",
      description: "Computer Hardware",
      uqc: "PCS",
      quantity: 150,
      taxableValue: "₹625,000",
      taxRate: "18%",
      cgst: "-",
      sgst: "-",
      igst: "₹112,500",
    },
    {
      hsnCode: "490110",
      description: "Printed Materials",
      uqc: "KGS",
      quantity: 2500,
      taxableValue: "₹170,000",
      taxRate: "12%",
      cgst: "₹10,200",
      sgst: "₹10,200",
      igst: "₹14,400",
    },
  ],
};
