import Badge from "@/components/common/Badge";

export const subTaskTableColumns = [
  { label: "S.No", key: "sno" },
  { label: "Task Name", key: "taskName" },
  { label: "Sub Task", key: "subTask" },
  { label: "Department", key: "department" },
  { label: "Mode", key: "mode" },
  { label: "Reporting Manager", key: "manager" },
  { label: "Created", key: "createdAt" },
  {
    label: "Remarks",
    key: "remarks",
    render: (value) => (
      <span className="text-gray-500 text-sm truncate">
        {value}
      </span>
    ),
  },
];

export const subTaskTableData = [
  {
    id: 1,
    sno: 1,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/1",
  },
  {
    id: 2,
    sno: 2,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/2",
  },
  {
    id: 3,
    sno: 3,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/3",
  },
  {
    id: 4,
    sno: 4,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/4",
  },
  {
    id: 5,
    sno: 5,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/5",
  },
  {
    id: 6,
    sno: 6,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/6",
  },
  {
    id: 7,
    sno: 7,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/7",
  },
  {
    id: 8,
    sno: 8,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/8",
  },
  {
    id: 9,
    sno: 9,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/9",
  },
  {
    id: 10,
    sno: 10,
    taskName: "Task-1",
    subTask: "GSTR-1",
    department: "Account",
    mode: "One Time",
    manager: "Charles Hather",
    createdAt: "1-Dec-2025",
    remarks: "Write a remark...",
    route: "/task-management/sub-task/10",
  },
];

