import Badge from "@/components/common/Badge";
import {
  EditAction,
  DeleteAction,
  SubTask,
} from "@/components/atoms/Icons";

export const taskTableColumns = [
  { label: "Task Name", key: "taskName" },
  { label: "Department", key: "department" },
  { label: "Mode", key: "mode" },
  { label: "Reporting Manager", key: "manager" },
  { label: "Created", key: "createdAt" },
  {
    label: "Remarks",
    key: "remarks",
    render: (value) => (
      <span className="text-gray-500 text-sm">{value}</span>
    ),
  },
  {
    label: "Status",
    key: "status",
  },
];

export const taskTableActions = [
  EditAction,
  DeleteAction,
  SubTask,
];

export const taskTableData = [
  {
    id: 1,
    taskName: 1,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/1`,
  },
  {
    id: 2,
    taskName: 2,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/2`,
  },
  {
    id: 3,
    taskName: 3,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/3`,
  },
  {
    id: 4,
    taskName: 4,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/4`,
  },
  {
    id: 5,
    taskName: 5,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/5`,
  },
  {
    id: 6,
    taskName: 6,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/6`,
  },
  {
    id: 7,
    taskName: 7,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/7`,
  },
  {
    id: 8,
    taskName: 8,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/8`,
  },
  {
    id: 9,
    taskName: 9,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/9`,
  },
  {
    id: 10,
    taskName: 10,
    department: "Account Department",
    mode: "One Time",
    manager: "Charlie Hather",
    createdAt: "23-Nov-2025",
    remarks: "Write a remarks",
    status: <Badge text="active" />,
    route: `/task-management/task/10`,
  },
];
