import Badge from "@/components/common/Badge";
import Profile from "@/components/common/Profile";

export const userColumns = [
  { label: "S.No", key: "id" },
  {
    label: "User Name",
    key: "name",
    render: (v, row) => (
      <Profile
        icon={row.name[0]}
        name={row.name}
        desc={row.phone}
        size="sm"
      />
    ),
  },
  { label: "Email", key: "email" },
  { label: "Role", key: "role" },
  { label: "Sales Invoice", key: "sales" },
  { label: "Created", key: "created" },
  { label: "Shop GST No", key: "gst" },
  { label: "Status", key: "status" },
];

export const userData = [
  {
    id: 1,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/1",
  },
 {
    id: 2,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/2",
  },
  {
    id: 3,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/3",
  },
  {
    id: 4,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/4",
  },
  {
    id: 5,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/5",
  },
  {
    id: 6,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/6",
  },
  {
    id: 7,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/7",
  },
  {
    id: 8,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/8",
  },
  {
    id: 9,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/9",
  },
  {
    id: 10,
    name: "John",
    phone: "+547372829",
    email: "john@gmail.com",
    role: "ABCD",
    sales: 12,
    created: "23-Nov-2025",
    gst: "22ABCDE1234FZ5",
    status: <Badge text="Active" />,
    route: "/staff-management/user/10",
  }
];
